### ISSUE TITLE
Do not set a default for MaxAckPending

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-architecture-and-design#100]
## Overview

Some clients have set a MaxAckPending (when not explicitly set by the user) to a very high value. Library should leave this non-set and let the server pick its default.
However, the library may want to ensure that the NATS subscription's pending limits are covering the MaxAckPending value.

## Clients and Tools

 - [x] CLI @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Ruby @wallyqs
 - [x] Rust @Jarema
   
## Other Tasks

 - [x] docs.nats.io updated
 - [ ] Update ADR to `Implemented`
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by scottf** [comment]
@kozlovic So currently the java and .net clients already do not set a default Max Ack Pending, i.e. don't send it unless the user sets a value. BUT the server currently returns 20,000 instead of leaving it blank, which I rely on to as equivalent to unset by the user. Can the server be changed to not return a value if the consumer was created without one?

**Comment by kozlovic** [comment]
@scottf No, the server has to set a value, which defaults to 20000 indeed. I am not sure what you mean by: "which I rely on to as equivalent to unset by the user".

**Comment by kozlovic** [comment]
> the server to set them but something is returned.

Because this is the actual consumer configuration. The server needs to set values that are persisted and return to consumer info APIs (or response to create).

> we check for an exact match of the consumer configuration

And I mentioned in the past that the configuration check needs to ignore values that have not been explicitly set by the user. So for instance in Go this would look like:
```
	if u.MaxAckPending > 0 && u.MaxAckPending != s.MaxAckPending {
		return makeErr("max ack pending", u.MaxAckPending, s.MaxAckPending)
	}
```
when `u` is the config from the user, and `s` from the "server" (the consumer info we get back from the server). So we check only if explicitly set.

**Comment by caspervonb** [comment]
No change needed in the Rust client as far as I can tell, already an optional value `Option<i64>` which has no default behavior if not set.
