### ISSUE TITLE
Remove Fetch Batch size limit

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#109]
## Overview

The original ADR specified that fetch batch limit should be enforced by the client at 256. This has changed and the ADR has been updated. Clients that enforce a limit should be changed to remove

The behavior is documented in ADR-13 which has been recently updated for this change. https://github.com/nats-io/nats-architecture-and-design/pull/108

## Clients and Tools

 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Ruby @wallyqs
 - [x] Rust @matthiashanel @derekcollison @Jarema
   
## Other Tasks

 - [x] docs.nats.io updated

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by aricart** [comment]
The javascript clients didn't enforce any limit or lack of, as ultimately the nats-server should be the one to accept or reject protecting itself.
