### ISSUE TITLE
Consumer configuration can accept a number of replicas

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#130]
## Overview

From the schema:

```
"num_replicas": {
  "description": "When set do not inherit the replica count from the stream but specifically set it to this amount",
  "type": "integer",
  "minimum": 0,
  "maximum": 5,
  "$comment": "integer with a dynamic bit size depending on the platform the cluster runs on, can be up to 64bit"
},
```

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs, @piotrpio
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Ruby @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated @jnmoyne
 - [x] Update client features spreadsheet

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by marthaCP** [comment]
All items completed; added to Parity sheet on 10/27/22
