### ISSUE TITLE
Consumer configuration can accept a mem storage flag

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#134]
## Overview

From the schema:

```
"mem_storage": {
  "description": "Force the consumer state to be kept in memory rather than inherit the setting from the stream",
  "type": "boolean",
  "default": false
}
```

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs, @piotrpio
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Ruby @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated @jnmoyne
 - [x] Update client features spreadsheet

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by marthaCP** [comment]
All actions completed and added to parity sheet on 10/27/22
