### ISSUE TITLE
Stream Republish

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-architecture-and-design#139]
## Overview

Streams are now able to republish on-boarded messages using NATS core.

[The behavior is documented in ADR 28.](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-28.md)

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs, @piotrpio
 - [x] Java @scottf
 - [x] JavaScript @aricart https://github.com/nats-io/nats.deno/blob/main/nats-base-client/types.ts#L1782-L1802, https://github.com/nats-io/nats.deno/blob/main/nats-base-client/types.ts#L1782-L1802,  https://github.com/nats-io/nats.deno/blob/main/tests/jetstream_test.ts#L3479-L3512
 - [x] .Net @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Ruby @wallyqs
 - [x] Rust Tomasz
   
## Other Tasks

 - [x] docs.nats.io updated @jnmoyne
 - [x] Update ADR to `Implemented`

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by Jarema** [comment]
implemented for Rust in https://github.com/nats-io/nats.rs/pull/613
