### ISSUE TITLE
Handle unsigned 64 bit server values.

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#17]
## Overview

Ensure client handles unsigned 64 bit server values.

The behavior is documented in ADR-1.

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart (unable to perform in JS)
 - [x] .Net @ColinSullivan1
 - [x] C 
 - [x] Python @wallyqs
 - [x] Rust @spacejam
   
## Other Tasks

 - [ ] docs.nats.io updated
 - [x] Update ADR to `Implemented`
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by ripienaar** [comment]
I've added type hints for int, uint64, int32 and time.Duration to the schemas via https://github.com/nats-io/jsm.go/pull/298

**Comment by scottf** [comment]
At the current time, these values are uint64

- `stream_source.opt_start_seq`
- `stream_source_info.lag`
- `lost_stream_data.msgs`
- `lost_stream_data.bytes`
- `stored_message.seq`
- `start_sequence_deliver_policy.opt_start_seq`
- `sequence_pair.consumer_seq`
- `sequence_pair.stream_seq`
- `consumer_info.num_pending`
- `consumer_configuration.rate_limit_bps`
- `stream_state.messages`
- `stream_state.bytes`
- `stream_state.first_seq`
- `stream_state.last_seq`
- `stream_state.deleted` _array_
- `stream_configuration.max_msgs`
- `stream_configuration.max_msgs_per_subject`
- `stream_configuration.max_bytes`

**Comment by aricart** [comment]
this is non-sensical, in some environments it will not be possible to do this (ie, unsigned is not supported, or the range of the number will max integer values.

**Comment by scottf** [comment]
Java is a good example where uint64 is not supported. We considered to make our own uint64 object, but since this would not have been a language primitive and since the int64 has quite a large value, we did not make changes and will have to deal with the consequences if some installation ends up with more than 9,223,372,036,854,775,807 messages we'll worry about it then.
@aricart Are there any languages that you are concerned about that do not even support int64? Target hardware that might now?

**Comment by aricart** [comment]
The javascript stack is spec'ed at `2^53 - 1`, on internal testing it seems to work with other things, but unsigned is not one of the options in that environment, so some values could appear negative. To be honest, the sequence is derived from a string (subject) so perhaps the thing to address is to just deal with these values as strings. The only wrinkle is any client trying to understand a sequence numerically.

**Comment by bruth** [comment]
@aricart I am sure you know this, but just wanted to call out [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) for the sake of this issue.

**Comment by aricart** [comment]
> @aricart I am sure you know this, but just wanted to call out [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) for the sake of this issue.

of course, it just requires an API change in all the models, and any value that is reported in JSON would likely require a custom JSON parsing library.

**Comment by bruth** [comment]
I was unaware of that you could [augment](https://stackoverflow.com/a/69644630/407954) the native `JSON.parse`.

**Comment by bruth** [comment]
@scottf Given that everything other than the explicit docs have been checked off (I am not sure what would stated in the docs since this is language specific), are you comfortable closing this?

**Comment by scottf** [comment]
Yes, fine to close.
