### ISSUE TITLE
Numbering and organization for ADRs

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#2]
Should client and server ADRs be in separate folders?

If ADRs are in same folder should there be a file naming convention 

1. with a server/client qualifier i.e. nnnn-server-title...md / nnnn-client-title...md 
2. numbering prefix i.e. 0001 for server, 5001 for client
2. both a numbering and a qualifier

If ADRs are in different folders should there be a naming convention
1. both files sets start at 0001 
2. server starts at 0001 and client starts at 5001

If ADRs are in different folders should there be a naming convention that requires a file naming qualifier.

**Comment by ripienaar** [comment]
The ADR format is not something we designed. It’s in use by many projects and standard tooling for this already exist

it’s a directory with sequentially files as per the example in the server.  

Is it perfect? No. But it’s a standard process. Please follow along.
