### ISSUE TITLE
Receive responses from multiple subscribers for a single request

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#215]
One of the most common questions we get is how to do request-reply but get response from all subscribers, not just the first one. Currently the way to do it is publish a message with a reply-to and at the same time to subscribe to the reply-to address.

Since this is such a common ask, we should consider how to add it to the clients.

**Comment by ripienaar** [comment]
Cli has --replies for this purpose, so will unassign myself.

**Comment by aricart** [comment]
The javascript client handles this via the `requestMany()` apis.

**Comment by tbeets** [comment]
Agree @scottf.  Although easy for developer to hand-roll, scatter-gather comes up often enough that a library-provided facility like @aricart describes makes sense.  

I think the usual push back is useful options for "get response from all subscribers", i.e. timer based, count based (with expiry), etc.   What tactic used for `requestMany()` @aricart ?

**Comment by wallyqs** [comment]
Also need to consider using the single resp mux to keep track of responses as an alternative to creating an inbox subscription for the batch of requests.

**Comment by ColinSullivan1** [comment]
Adding a convenience API would be nice - # of responses to expect, timeout, and return an array/list/slice of messages. This is a very common ask...

**Comment by aricart** [comment]
@tbeets you have to implement several strategies:
- Timer
- Count
- Sentinel Message
- Jitter Timer

The jitter is the secret sauce, when you specify that, as long as messages are arriving, the jitter is reset (100ms or so). So this means you make a request with a 2s timeout, but as soon as you get one response, the jitter timer takes over and is reset with each new message. If no messages arrive within the jitter, then the request is done. With jitter most count/expected type things work correctly without having an absolute stop timer

Sentinel, is empty payload

The API works with both mux and no mux inboxes

**Comment by scottf** [comment]
Closing as being addressed with ADR
