### ISSUE TITLE
Consumer Configuration Max Waiting

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#24]
## Overview

Consumer Max [Pull] Waiting Messages is a new field in consumer_configuration.

```
    "max_waiting": {
      "description": "The number of pulls that can be outstanding on a pull consumer, pulls received after this is reached are ignored",
      "minimum": 0,
      "default": 512,
      "$comment": "integer with a dynamic bit size depending on the platform the cluster runs on, can be up to 64bit",
      "type": "integer",
      "maximum": 9223372036854775807
    },
```

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript 
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @spacejam
   
## Other Tasks

 - [x] docs.nats.io updated
 - [ ] Update ADR to `Implemented`
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by aricart** [comment]
@scottf can you fix the reference to `ADR-X`, also are there any client expected changes other than possibly setting the value.

**Comment by scottf** [comment]
fixed. No adr, just a field to add

**Comment by caspervonb** [comment]
Seems like this has already landed nats.rs and can be marked as complete: https://github.com/nats-io/nats.rs/blob/main/src/jetstream_types.rs#L132

**Comment by bruth** [comment]
Appears Python supports this as early as https://github.com/nats-io/nats.py/pull/216 /cc @wallyqs

**Comment by bruth** [comment]
Present in [docs](https://docs.nats.io/nats-concepts/jetstream/consumers#maxwaiting) and no ADR, so closing.
