### ISSUE TITLE
QUIC as secure transport

### ISSUE THREAD

**Issue by sylr** [nats-io/nats-architecture-and-design#257]
## Overview

Add QUIC as transport protocol within NATS ecosystem (client<->server, server<->server).

## Clients and Tools

 - [ ] Schemas @ripienaar
 - [ ] CLI @ripienaar
 - [ ] Terraform @ripienaar
 - [ ] Github Actions @ripienaar
 - [ ] Go @piotrpio
 - [ ] Java @scottf
 - [ ] JavaScript @aricart
 - [ ] .Net @scottf
 - [ ] C @levb
 - [ ] Python @wallyqs
 - [ ] Ruby @wallyqs
 - [ ] Rust @Jarema @caspervonb
 - [ ] .Net V2 @mtmk

## Other Tasks

 - [ ] docs.nats.io updated @bruth
 - [ ] Update ADR to `Implemented`
 - [ ] Update client features spreadsheet

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by ripienaar** [comment]
Better to track the server issue here than open an issue in this repository for it.

https://github.com/nats-io/nats-server/issues/3140
