### ISSUE TITLE
Implement Pull Consumer Priority Groups

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#307]
## Overview

The behavior is documented in [ADR-42](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-42.md).

## Clients and Tools

 - [ ] Schemas @ripienaar
 - [ ] CLI @ripienaar
 - [ ] Terraform @ripienaar
 - [ ] Github Actions @ripienaar
 - [ ] Go @piotrpio https://github.com/nats-io/nats.go/pull/1702
 - [ ] Java @scottf
 - [ ] JavaScript @aricart
 - [ ] .Net @scottf
 - [ ] C @levb
 - [ ] Python @caspervonb
 - [ ] Ruby @wallyqs
 - [ ] Rust @Jarema
 - [ ] .Net V2 @mtmk

## Other Tasks

 - [ ] docs.nats.io updated @bruth
 - [ ] Update ADR to `Implemented`
 - [ ] Update client features spreadsheet

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by ripienaar** [comment]
Note we specifically are NOT implementing this in all the clients initially while we learn from the work JNM is doing in go

**Comment by scottf** [comment]
Closed for now
