### ISSUE TITLE
Stream and Consumer Descriptions

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#32]
## Overview

API Clients can now put descriptions into Stream and Consumer configuration, especially helpful to figure out what ephemeral consumers are for etc

Server PR https://github.com/nats-io/nats-server/pull/2377

Make sure to json encode the value

## Clients and Tools

 - [x] Schemas @ripienaar https://github.com/nats-io/jsm.go/pull/301
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript 
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [ ] docs.nats.io updated
 - [ ] Update ADR to `Implemented`
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
PR opened for docs, no ADR, all clients completed.
