### ISSUE TITLE
last_per_subject delivery policy

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#33]
## Overview

The new `last_per_subject` delivery policy delivers the last message received in any subject matched by the consumer filter in a wildcard stream

Server PR https://github.com/nats-io/nats-server/pull/2381

## Clients and Tools

 - [x] Schemas @ripienaar https://github.com/nats-io/jsm.go/pull/304
 - [x] CLI @ripienaar https://github.com/nats-io/natscli/pull/205
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Rework KV ADR and reference implementation @ripienaar https://github.com/nats-io/nats-architecture-and-design/pull/30
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart https://github.com/nats-io/nats.deno/pull/178
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by aricart** [comment]
javascript is done.

**Comment by bruth** [comment]
Python support in https://github.com/nats-io/nats.py/pull/259

**Comment by bruth** [comment]
Rust support in https://github.com/nats-io/nats.rs/pull/471 /cc @Jarema
