### ISSUE TITLE
Push Consumer active information and queue group binding

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#43]
## Overview

A number of Push related changes were made:

A new ConsumerInfo boolean `push_bound` indicates if any subscriber is currently active on a Push Consumer.  Additionally a new property `deliver_group` instructs the server to only deliver messages to subscriptions matching a queue group of `deliver_group`.

On the Sequence Pairs for ack floor and delivered is a new timestamp that shows when last message was ACKed (not NAK or Term) and when last a message was delivered

Server PR https://github.com/nats-io/nats-server/pull/2438
See ADR: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-15.md
section: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-15.md#push-consumer-active-information-and-queue-group-binding

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar 
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript 
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] Update the JS Context Subscribe behavior ADR if not in there already
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by ripienaar** [comment]
HOLD on this one, we're changing how this works.

**Comment by ripienaar** [comment]
> HOLD on this one, we're changing how this works.

This is ready to implement, the approach has been redesigned, description schemas etc updated.

**Comment by aricart** [comment]
@ripienaar can you elaborate on what the behavior should be from the client's perspective on `deliver_group`. I would assume that this would be:

- set on the consumer creation if a group was specified
- In cases where the consumer already exists, if the consumer doesn't specify the queue group or the queue group name is different the client should reject

**Comment by ripienaar** [comment]
@aricart I think @kozlovic is probably most on top of what is expected from clients on this one

**Comment by kozlovic** [comment]
I will update the ADR PR about subscribe flow later today with what was done in the Go PR #794 over the week-end.

**Comment by kozlovic** [comment]
This is described in here: https://github.com/nats-io/nats-architecture-and-design/pull/42/files#diff-f52a7740d240a96a07d8e7f9a40d3eb460cee1176914ea5ae1d76175f0d140bdR89. Will update this when the PR is merged to main branch.

**Comment by bruth** [comment]
In Rust as of https://github.com/nats-io/nats.rs/pull/252 /cc @Jarema

**Comment by bruth** [comment]
In Python as of https://github.com/nats-io/nats.py/pull/222 /cc @wallyqs
