### ISSUE TITLE
Domain in JetStream Pub Ack

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#44]
## Overview

2 domains can host a stream with the same name, the PubAck only included the Stream name making it hard to know if the message went to the desired location.  It now also includes the domain.

Server PR https://github.com/nats-io/nats-server/pull/2432

new Struct is:
```
type PubAck struct {
	Stream    string `json:"stream"`
	Sequence  uint64 `json:"seq"`
	Domain    string `json:"domain,omitempty"`
	Duplicate bool   `json:"duplicate,omitempty"`
}
```

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [ ] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Python support as of https://github.com/nats-io/nats.py/pull/216

**Comment by bruth** [comment]
Regarding docs, this will generated as part of reference docs from the JSON schema definitions.
