### ISSUE TITLE
Allow user to supply full prefix or just domain

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#52]
## Overview

1. Accept full prefix, turning `$JS.API.` into `<prefix>.API.`
2. Accept domain, turning `$JS.API.` into `$JS.<domain>.API.`

## Clients and Tools

 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Appears to be completed, closing.
