### ISSUE TITLE
Support sealing streams

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#58]
## Overview

When a stream is sealed it cannot have new messages added or messages removed and it cannot be unsealed.  Limits also do not apply to a sealed stream - messages will not age out.

Streams can only be sealed via update, not during create time.

Server PR https://github.com/nats-io/nats-server/pull/2584

### Client Actions
1. A client should report the Stream Configuration `sealed` value as it receives it from the server.
1. If a sealed stream is published to, the server will throw an error. Pass this to the user.

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Support in Rust as of https://github.com/nats-io/nats.rs/pull/256 /cc @Jarema

**Comment by bruth** [comment]
Support in Python as of https://github.com/nats-io/nats.py/pull/216 /cc @wallyqs

**Comment by bruth** [comment]
PR for docs: https://github.com/nats-io/nats.docs/pull/482
