### ISSUE TITLE
Support Per stream modification permissions

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#60]
## Overview

Streams have several new permissions that allow one to prevent deletes, purges and enable rollups.

Server PRs https://github.com/nats-io/nats-server/pull/2595

Schema updates in https://github.com/nats-io/jsm.go/pull/333

Required for completion of ADR-8

### Fields

ConsumerConfiguration `headers_only`
StreamConfiguration `deny_delete`
StreamConfiguration `deny_purge`
StreamConfiguration `allow_rollup_hdrs`

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs (https://github.com/nats-io/nats.go/pull/832)
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Python support in https://github.com/nats-io/nats.py/pull/216 /cc @wallyqs

**Comment by bruth** [comment]
PR for docs: https://github.com/nats-io/nats.docs/pull/482
