### ISSUE TITLE
Support header only consumers

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#61]
## Overview

Consumers have an option to enable delivering just headers. When delivering just headers an additional header Nats-Msg-Size is added indicating the size of the omitted body.

Server PR https://github.com/nats-io/nats-server/pull/2596
Schemas in https://github.com/nats-io/jsm.go/pull/333

These features are required for ADR-8

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar (https://github.com/nats-io/natscli/pull/259)
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs (https://github.com/nats-io/nats.go/pull/832)
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Python implemented in https://github.com/nats-io/nats.py/pull/216
Docs PR here; https://github.com/nats-io/nats.docs/pull/482
