### ISSUE TITLE
Ordered Consumer

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-architecture-and-design#62]
## Overview

Implement Ordered Consumer as documented in https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-17.md

## Clients and Tools

 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] Update ADR to `Implemented`
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Anything left to do other than update the ADR doc?
