### ISSUE TITLE
Support updating consumers

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#74]
## Overview

Consumers now support updating  description, ack_wait, max_deliver, sample_freq, max_ack_pending, max_waiting and headers_only.

## Clients and Tools

 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript @aricart
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Ruby @wallyqs (not supported at this time)
 - [x] Rust @Jarema 
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by bruth** [comment]
Checked off the docs as @jnmoyne did this in https://github.com/nats-io/nats.docs/pull/478
