### ISSUE TITLE
Add the ability to get a range of matching keys from a bucket

### ISSUE THREAD

**Issue by boxboatmatt** [nats-io/nats-architecture-and-design#81]
## Overview

Add a method to `KeyValue` interface for a key range to be returned. For example if you want to get a list of all keys in a bucket that start with `a.b.`

ADR-8

## Clients and Tools

 - [ ] Schemas @ripienaar
 - [ ] CLI @ripienaar
 - [ ] Terraform @ripienaar
 - [ ] Github Actions @ripienaar
 - [ ] Go @piotrpio 
 - [ ] Java @scottf
 - [ ] JavaScript @aricart
 - [ ] .Net @scottf
 - [ ] C @kozlovic
 - [ ] Python @wallyqs
 - [ ] Ruby @wallyqs
 - [ ] Rust @Jarema 
   
## Other Tasks

 - [ ] docs.nats.io updated
 - [ ] Update ADR to `Implemented`
 - [ ] Update client features spreadsheet

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by aricart** [comment]
This operation is actually possible (at least in the JavaScript client) - you can get all the keys that match your query and then retrieve their values by iteration.
