### ISSUE TITLE
Support MaxMsgsPer for streams

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#9]
## Overview

A new property allows JetStream to track messages per subject rather than the entire stream.  That is `MaxMsgsPerSubject: 5` would allow 5 messages in `x.y` and 5 messages in `x.z`.

There is no ADR it's a minor feature. Server PR https://github.com/nats-io/nats-server/pull/2284

`stream_configuration` -> `max_msgs_per_subject`

## Clients and Tools

 - [x] Schemas @ripienaar
 - [x] CLI @ripienaar
 - [x] Terraform @ripienaar
 - [x] Github Actions @ripienaar
 - [x] Go @wallyqs
 - [x] Java @scottf
 - [x] JavaScript 
 - [x] .Net @ColinSullivan1 @scottf
 - [x] C @kozlovic
 - [x] Python @wallyqs
 - [x] Rust @spacejam
   
## Other Tasks

 - [x] docs.nats.io updated
 - [x] [Update client features spreadsheet](https://docs.google.com/spreadsheets/d/1VcYcKqwOp8h8zZwNSRXMS5wrdA1jZz6AumMTHZbXrmY/edit?usp=sharing)

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by kozlovic** [comment]
Again, commit may disappear when ready for PR, etc.. but done in the C client: https://github.com/nats-io/nats.c/commit/2867903297232aacae8b51754a9ebe2514c27f72

**Comment by sloveridge** [comment]
Merged into Go client https://github.com/nats-io/nats.go/commit/c8db2d38925927f44bfbf270dfbce485097941db

**Comment by caspervonb** [comment]
Merged into Rust client https://github.com/nats-io/nats.rs/commit/80a2ed1932c7c59669e049ef95c8f0610c390282

**Comment by bruth** [comment]
Documented as of https://github.com/nats-io/nats.docs/pull/495
